feat: github actions pipeline

diff --git a/backend/Makefile b/backend/Makefile
--- a/backend/Makefile
+++ b/backend/Makefile
@@ -8,3 +8,20 @@ test-grpc:
 	--schema ../proto \
 	--data "{\"histories\":[{\"date\":\"2024-12-07\",\"user\":{\"userId\":\"123\",\"name\":\"太郎\",\"role\":2},\"message\":\"今度ご飯にいきませんか？\"}],\"actionKind\":2}" \
 	http://localhost:50051/backend.v1.BackendService/Talk
+
+.PHONY: tools
+tools:
+	@if ! which golangci-lint > /dev/null; then \
+		echo "golangci-lint not found, installing..."; \
+		go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.1; \
+	else \
+		echo "golangci-lint already installed, skipping..."; \
+	fi
+
+.PHONY: lint
+lint: tools
+	golangci-lint run ./... --timeout=5m
+
+.PHONY: format
+format: tools
+	golangci-lint run ./... --fix
